sonar.projectKey=minimarket-ecommerce
sonar.projectName=minimarket-ecommerce
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.tests=test/unit
sonar.test.inclusions=test/unit/**/*.test.js
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/lcov.info