name: CI/CD - Node + SonarQube + Docker

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  APP_CONTAINER_NAME: node-app
  DB_CONTAINER_NAME: node-db

jobs:

  sonar-analysis:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      # 🔥 FIX REAL AQUÍ
      - name: SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          echo "TOKEN LENGTH: ${#SONAR_TOKEN}"

          if [ -z "$SONAR_TOKEN" ]; then
            echo "ERROR: SONAR_TOKEN is empty"
            exit 1
          fi

          /opt/sonar-scanner/bin/sonar-scanner \
            -Dsonar.projectKey=node-project \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login=$SONAR_TOKEN

  build-and-deploy:
    runs-on: self-hosted
    needs: sonar-analysis

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and run Docker
        run: |
          docker compose down -v
          docker compose up -d --build

      - name: Show logs
        run: |
          docker ps
          docker logs --tail 50 $APP_CONTAINER_NAME